version: 2.1
orbs:
 grafana: grafana/k6@1.0.1
workflows:
  performance:
   jobs:
     - grafana/k6:
         cloud: false
         script: loadtests/performance-test.js --out json=full.json > /tmp/artifacts
         arguments: --quiet
  daily:
    triggers:
      - schedule:
          cron: "35 13 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - grafana/k6:
         cloud: false
         script: loadtests/performance-test.js --out json=full.json > /tmp/artifacts
         arguments: --quiet