version: 2.1
orbs:
 grafana: grafana/k6@1.0.1
workflows:
  pullrequest-performance:
   jobs:
     - grafana/k6:
         cloud: false
         script: browsertests/simple-test.js --out json=full.json > /tmp/artifacts
         arguments: --quiet
  daily-performance:
    triggers:
      - schedule:
          cron: "0 9 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - grafana/k6:
         cloud: false
         script: loadtests/performance-test.js --out json=full.json > /tmp/artifacts
         arguments: --quiet
  nightly-performance:
    triggers:
      - schedule:
          cron: "0 22 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - grafana/k6:
         cloud: false
         script: loadtests/performance-test.js --out json=full.json > /tmp/artifacts
         arguments: --quiet