version: 2.1
orbs:
 grafana: grafana/k6@1.0.1
workflows:
  load_test:
   jobs:
     - grafana/k6:
         cloud: false
         script: loadtests/performance-test.js
         arguments: --quiet
  daily:
    triggers:
      - schedule:
          cron: "10 14 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - grafana/k6
